#!/bin/bash

set -euf

f="$1"

case "$f" in
  *.tar.bz|*.tar.bz2|*.tbz|*.tbz2) tar xjvf "$f";;
  *.tar.gz|*.tgz) tar xzvf "$f";;
  *.tar.xz|*.txz) tar xJvf "$f";;
  *.zip)
    if type ditto >/dev/null 2>&1; then
      ditto -V -x -k "$f" .
    else
      unzip "$f"
    fi
    ;;
  *.rar) unrar x "$f";;
  *.7z|*.z*) 7z x "$f";;
esac
