#!/bin/sh

case "$1" in
  *.tar*)
    tar tf "$1"
    ;;
  *.zip)
    unzip -l "$1"
    ;;
  *.rar)
    unrar l "$1"
    ;;
  *.7z)
    7z l "$1"
    ;;
  *.pdf)
    pdftotext "$1" -
    ;;
  *.jpg|*.jpeg|*.png)
    chafa --colors=256 "$1"
    ;;
  *)
    unset COLORTERM
    bat --color=always --line-range=0:"$2" --paging=never --plain "$1"
    ;;
esac
