#!/bin/sh

set -euf

command_exists() {
  type "${1}" >/dev/null 2>&1
}

case "$1" in
  *.tar*)
    tar tf "$1"
    ;;
  *.zip)
    unzip -l "$1"
    ;;
  *.rar)
    unrar l "$1"
    ;;
  *.7z)
    7z l "$1"
    ;;
  *.pdf)
    pdftotext "$1" -
    ;;
  *.jpg|*.jpeg|*.png)
    if command_exists chafa; then
      chafa --colors=256 "$1"
    elif command_exists viu; then
      viu -w "$2" "$1"
    fi
    ;;
  *)
    unset COLORTERM
    bat --color=always --line-range=0:"$2" --paging=never --plain "$1"
    ;;
esac
