#!/usr/bin/env bash

# Return if not interactive shell
[[ $- != *i* ]] && return

if [ -z "${debian_chroot:-}" ] && [ -r /etc/debian_chroot ]; then
  debian_chroot=$(cat /etc/debian_chroot)
fi

[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# Bash Completion
if [ -f /etc/bash_completion ]; then
  source /etc/bash_completion
fi

export EDITOR="vim"
export PAGER="less"

if type chezmoi >/dev/null 2>&1; then
  export DOTFILES=$(chezmoi source-path)
  export DOTFILES_MODULES="${DOTFILES}/.modules"

  _USER_SCRIPTS="${DOTFILES}/.scripts.sh"
  _USER_BIN="${HOME}/.local/bin"

  export PATH="${_USER_SCRIPTS}:${_USER_BIN}:${PATH}"

  source "${DOTFILES_MODULES}/bash/init.bash"

  source "${DOTFILES_MODULES}/aliases.sh"
  source "${DOTFILES_MODULES}/go.plugin.sh"
  source "${DOTFILES_MODULES}/gpg.plugin.sh"
  source "${DOTFILES_MODULES}/python.plugin.sh"
  source "${DOTFILES_MODULES}/ruby.plugin.sh"
  source "${DOTFILES_MODULES}/rust.plugin.sh"

  source "${DOTFILES_MODULES}/fzf.plugin.sh"
  source "${DOTFILES_MODULES}/lf.plugin.sh"
fi
